function [ rgb_image ] = render( particles_matrix )
%RENDER Summary of this function goes here
%   Detailed explanation goes here
rgb_image = permute(reshape([particles_matrix.color],...
                    3,...
                    size(particles_matrix, 1),...
                    size(particles_matrix, 2)),...
                    [2 3 1]);
end

